language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
env:
  global:
    - PACKAGE_VERSION: "0.0.1" 
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest